using NotificationService.Models.Dtos;
using NotificationService.Models.Entities;

namespace NotificationService.MappingExtensions;

public static class NotificationMappingExtensions
{
    public static NotificationEntity ToEntity(this NotificationDto dto) => new()
    {
        // Id = Guid.NewGuid(), // Assuming Id is generated here
        NotificationType = dto.NotificationType,
        SourceEntityId = dto.SourceEntityId,
        TriggeringUserId = dto.TriggeringUserId,
        Timestamp = dto.Timestamp,
        TargetFarmId = dto.TargetFarmId,
        TargetUserId = dto.TargetUserId,
        IsRead = dto.IsRead
    };


    public static NotificationDto ToDto(this NotificationEntity entity) => new(
        entity.Id, // Assuming Id is generated by the database
        entity.NotificationType,
        entity.SourceEntityId,
        entity.TriggeringUserId,
        entity.Timestamp,
        entity.TargetFarmId,
        entity.TargetUserId,
        entity.IsRead
    );
}