// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserProfileService.Data;

#nullable disable

namespace UserProfileService.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    [Migration("20250306110852_Added_Attributes")]
    partial class Added_Attributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileAttributeUserProfile", b =>
                {
                    b.Property<Guid>("ProfileAttributesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileAttributesId", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("UserProfileProfileAttribute", (string)null);
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.AttributeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AttributeCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "General Farm Labor"
                        },
                        new
                        {
                            Id = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Crop-Specific Roles"
                        },
                        new
                        {
                            Id = new Guid("f343ab87-eb1b-42fd-b11a-982ac0832fc0"),
                            IsPredefined = true,
                            Name = "Equipment Specialization"
                        },
                        new
                        {
                            Id = new Guid("4f957bf9-5829-4cb8-8b6f-e78fae5d1b9c"),
                            IsPredefined = true,
                            Name = "Role"
                        },
                        new
                        {
                            Id = new Guid("aa9487ef-7e74-467a-9e15-068db3529f02"),
                            IsPredefined = false,
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.ProfileAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProfileAttributes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc589e44-3c9a-436d-ac77-836f67ee80b3"),
                            CategoryId = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "General Farmhand/Laborer"
                        },
                        new
                        {
                            Id = new Guid("c2e5fb01-897d-4f17-b064-b6290663fef1"),
                            CategoryId = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "Field Worker"
                        },
                        new
                        {
                            Id = new Guid("a91a5b91-cddb-44a1-a538-5568db16d8e5"),
                            CategoryId = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "Equipment Operator"
                        },
                        new
                        {
                            Id = new Guid("98444a92-b679-44dc-91ba-7a69d0f561a2"),
                            CategoryId = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "Maintenance Worker"
                        },
                        new
                        {
                            Id = new Guid("32e8183f-90b2-4334-86c3-4d27c7b75b6f"),
                            CategoryId = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "Irrigation Technician"
                        },
                        new
                        {
                            Id = new Guid("c87a191b-dd53-473b-9e62-5557dfc8b133"),
                            CategoryId = new Guid("e41c22a3-7d8d-4d25-b0b2-3b23a5eebe9b"),
                            IsPredefined = true,
                            Name = "Livestock Handler"
                        },
                        new
                        {
                            Id = new Guid("2a94340d-13c9-4eae-98b1-1edcee38a468"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Planter"
                        },
                        new
                        {
                            Id = new Guid("c7330d5e-5471-4b39-a907-9bd3c4bcc23e"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Harvester"
                        },
                        new
                        {
                            Id = new Guid("1fed148c-5cbb-412d-a6db-51423db450b5"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Weed Control Specialist"
                        },
                        new
                        {
                            Id = new Guid("48f672f4-43c9-4bc5-ae98-d98b070cf8fa"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Pest Control Specialist"
                        },
                        new
                        {
                            Id = new Guid("ce81221b-95b6-41ec-8a3d-37c43d9aacb2"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Scout"
                        },
                        new
                        {
                            Id = new Guid("ed65cd35-f17c-4a47-bd55-aeba19a47d86"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Crop Specialist / Agronomist Assistant"
                        },
                        new
                        {
                            Id = new Guid("934182f1-6e90-46e0-bb58-2ae0e46c1c0a"),
                            CategoryId = new Guid("f6f8f617-1f24-475d-8366-b6476cc00ee9"),
                            IsPredefined = true,
                            Name = "Greenhouse Worker"
                        },
                        new
                        {
                            Id = new Guid("97d19c0d-cd03-43ca-ab57-63d70a18019c"),
                            CategoryId = new Guid("f343ab87-eb1b-42fd-b11a-982ac0832fc0"),
                            IsPredefined = true,
                            Name = "Tractor Operator"
                        },
                        new
                        {
                            Id = new Guid("35e11364-0de4-4840-b63c-095323e6de59"),
                            CategoryId = new Guid("f343ab87-eb1b-42fd-b11a-982ac0832fc0"),
                            IsPredefined = true,
                            Name = "Combine Operator"
                        },
                        new
                        {
                            Id = new Guid("0f2badb3-d2d1-47f2-a9ca-c77eece69fe8"),
                            CategoryId = new Guid("f343ab87-eb1b-42fd-b11a-982ac0832fc0"),
                            IsPredefined = true,
                            Name = "Sprayer Operator"
                        },
                        new
                        {
                            Id = new Guid("e82d6839-fbe1-4c32-8653-147caac1989b"),
                            CategoryId = new Guid("4f957bf9-5829-4cb8-8b6f-e78fae5d1b9c"),
                            IsPredefined = true,
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ProfileAttributeUserProfile", b =>
                {
                    b.HasOne("UserProfileService.Models.Entities.ProfileAttribute", null)
                        .WithMany()
                        .HasForeignKey("ProfileAttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserProfileService.Models.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.ProfileAttribute", b =>
                {
                    b.HasOne("UserProfileService.Models.Entities.AttributeCategory", "Category")
                        .WithMany("ProfileAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.AttributeCategory", b =>
                {
                    b.Navigation("ProfileAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
