// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserProfileService.Data;

#nullable disable

namespace UserProfileService.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    [Migration("20250306111846_GuidFix")]
    partial class GuidFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileAttributeUserProfile", b =>
                {
                    b.Property<Guid>("ProfileAttributesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileAttributesId", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("UserProfileProfileAttribute", (string)null);
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.AttributeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AttributeCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "General Farm Labor"
                        },
                        new
                        {
                            Id = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Crop-Specific Roles"
                        },
                        new
                        {
                            Id = new Guid("04c71678-4205-4a37-817b-92d05dc9fd72"),
                            IsPredefined = true,
                            Name = "Equipment Specialization"
                        },
                        new
                        {
                            Id = new Guid("fee5d6bf-3a86-4800-a309-d0b0a4af5168"),
                            IsPredefined = true,
                            Name = "Role"
                        },
                        new
                        {
                            Id = new Guid("da69270b-6390-428f-92ed-b077f512d31f"),
                            IsPredefined = false,
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.ProfileAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProfileAttributes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59a1672f-0c87-4ec5-b52e-1ec09065c7ee"),
                            CategoryId = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "General Farmhand/Laborer"
                        },
                        new
                        {
                            Id = new Guid("f5596fd6-ae03-4927-8a13-68e012a37d9d"),
                            CategoryId = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "Field Worker"
                        },
                        new
                        {
                            Id = new Guid("2366a79e-5332-4b68-897e-e7de174fa69c"),
                            CategoryId = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "Equipment Operator"
                        },
                        new
                        {
                            Id = new Guid("bd820d62-3e3c-4fad-9ad5-187fb055d9bf"),
                            CategoryId = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "Maintenance Worker"
                        },
                        new
                        {
                            Id = new Guid("3c4b4a67-d9f4-4b10-bc52-8be1f5de2643"),
                            CategoryId = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "Irrigation Technician"
                        },
                        new
                        {
                            Id = new Guid("19467a7f-2707-42be-8f7d-a179014936db"),
                            CategoryId = new Guid("a1ef0f83-97a7-49c5-b0bd-2f6fbd6cd102"),
                            IsPredefined = true,
                            Name = "Livestock Handler"
                        },
                        new
                        {
                            Id = new Guid("1c4e6180-9edb-4683-9afc-a0631dac381d"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Planter"
                        },
                        new
                        {
                            Id = new Guid("fab9ea3e-1589-45cb-98c8-9ed5c4148a38"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Harvester"
                        },
                        new
                        {
                            Id = new Guid("255c4fb4-76ed-4234-8ff5-9e7116224a40"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Weed Control Specialist"
                        },
                        new
                        {
                            Id = new Guid("a8a06283-6dd4-400d-8fd4-3800122d4856"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Pest Control Specialist"
                        },
                        new
                        {
                            Id = new Guid("093cefca-3ec1-4f52-a39c-62dedbc82a61"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Scout"
                        },
                        new
                        {
                            Id = new Guid("911c9119-6570-4070-9a0d-9a5301b9773b"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Crop Specialist / Agronomist Assistant"
                        },
                        new
                        {
                            Id = new Guid("5d85c8f3-774e-47f7-8b4b-5334f1a3722f"),
                            CategoryId = new Guid("e7aa259c-8b80-4a74-a99e-78d42f330a7c"),
                            IsPredefined = true,
                            Name = "Greenhouse Worker"
                        },
                        new
                        {
                            Id = new Guid("bb96978e-f161-4b91-98d8-eb7098727d77"),
                            CategoryId = new Guid("04c71678-4205-4a37-817b-92d05dc9fd72"),
                            IsPredefined = true,
                            Name = "Tractor Operator"
                        },
                        new
                        {
                            Id = new Guid("08312aa3-68b0-42a5-9522-aeebb5b4d85d"),
                            CategoryId = new Guid("04c71678-4205-4a37-817b-92d05dc9fd72"),
                            IsPredefined = true,
                            Name = "Combine Operator"
                        },
                        new
                        {
                            Id = new Guid("b00c6b53-65cd-43d5-a9a6-83149923a0ee"),
                            CategoryId = new Guid("04c71678-4205-4a37-817b-92d05dc9fd72"),
                            IsPredefined = true,
                            Name = "Sprayer Operator"
                        },
                        new
                        {
                            Id = new Guid("3fa29a42-7763-4c0d-b391-458de8e79a33"),
                            CategoryId = new Guid("fee5d6bf-3a86-4800-a309-d0b0a4af5168"),
                            IsPredefined = true,
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ProfileAttributeUserProfile", b =>
                {
                    b.HasOne("UserProfileService.Models.Entities.ProfileAttribute", null)
                        .WithMany()
                        .HasForeignKey("ProfileAttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserProfileService.Models.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.ProfileAttribute", b =>
                {
                    b.HasOne("UserProfileService.Models.Entities.AttributeCategory", "Category")
                        .WithMany("ProfileAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UserProfileService.Models.Entities.AttributeCategory", b =>
                {
                    b.Navigation("ProfileAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
