// <auto-generated />
using System;
using CropCatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CropCatalogService.Migrations
{
    [DbContext(typeof(CropCatalogDbContext))]
    [Migration("20250327144251_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CropCatalogService.Model.Entities.CropCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BinomialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DaysToFirstHarvest")
                        .HasColumnType("integer");

                    b.Property<int?>("DaysToLastHarvest")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("HarvestSeasonEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("HarvestSeasonStart")
                        .HasColumnType("date");

                    b.Property<string>("ImageLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsPerennial")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxMonthsToBearFruit")
                        .HasColumnType("integer");

                    b.Property<int?>("MinMonthsToBearFruit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SowingMethod")
                        .HasColumnType("text");

                    b.Property<string>("SunRequirements")
                        .HasColumnType("text");

                    b.Property<string>("WikipediaLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CropCatalogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
