using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries;

namespace PlantedCropsService.Models.Entities;

public class Crop
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Autogenerated Guid
    public Guid Id { get; set; }

    [Required] 
    public required string Name { get; set; }

    [Required] 
    public required string BinomialName { get; set; }

    public string? CultivatedVariety { get; set; }

    public string? ImageLink { get; set; }
    
    [Required, Column(TypeName = "date")]
    public required DateOnly PlantingDate { get; set; }

    [Required]
    public required bool Perennial { get; set; }

    [Column(TypeName = "date")] // Specify date type in database
    public DateOnly? ExpectedFirstHarvestDate { get; set; }

    [Column(TypeName = "date")] // Specify date type in database
    public DateOnly? ExpectedLastHarvestDate { get; set; }

    [Column(TypeName = "date")] // Specify date type in database
    public DateOnly? ExpectedFirstHarvestStartDate { get; set; }

    [Column(TypeName = "date")] // Specify date type in database
    public DateOnly? ExpectedFirstHarvestEndDate { get; set; }

    [Column(TypeName = "date")] // Specify date type in database
    public DateOnly? ExpectedLastHarvestStartDate { get; set; }

    [Column(TypeName = "date")] // Specify date type in database
    public DateOnly? ExpectedLastHarvestEndDate { get; set; }

    [Required] 
    public required Guid FieldId { get; set; }

    public Polygon? Surface { get; set; } // Store Polygon data, consider using spatial types

    [Required]
    public double? Area { get; set; }

    [Required] 
    public Guid CropCatalogId { get; set; }
    
    [Required]
    public required Guid FarmId { get; set; }

    // Navigation Properties
    public virtual ICollection<GrowthStageEvent> GrowthStageEvents { get; set; } = new List<GrowthStageEvent>();
    public virtual ICollection<FertilizerEvent> FertilizerEvents { get; set; } = new List<FertilizerEvent>();
    public virtual ICollection<HealthStatusEvent> HealthStatusEvents { get; set; } = new List<HealthStatusEvent>();
}